### ISSUE TITLE
How to Set a user and passwd?

### ISSUE THREAD

**Issue by skyleelove** [samuel/go-zookeeper#128]
When i connect zk, I need set user name and password, how i can do this in your sdk?

**Comment by samuel** [comment]
The connection object has an AddAuth method: https://godoc.org/github.com/samuel/go-zookeeper/zk#Conn.AddAuth

Note though there's a pending PR to fix re-submitting auth on reconnect: https://github.com/samuel/go-zookeeper/pull/139
