### ISSUE TITLE
sasl authentication

### ISSUE THREAD

**Issue by AnirudhVyas** [samuel/go-zookeeper#156]
How do I authenticate using SASL with the library? We have zook servers that are on SASL and need jaas conf supplied at the moment....

**Comment by sketkar** [comment]
@samuel Even i am trying to figure out how to authenticate using SASL. Does the library support that?

**Comment by AnirudhVyas** [comment]
I dont think it does ... I ended up building a scala client to zook and exposing a akka tcp endpoint to wrap around the problem

**Comment by AnirudhVyas** [comment]
Repo owners - Please respond to issues open so atleast we get a quick idea on where the project stands. I am closing this issue as there has been no update for 3 years. I have since moved on and was able to complete the project differently.
