### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by jhump** [samuel/go-zookeeper#249]
@samuel, is this a dead project? I notice a more active repo at go-zookeeper/zk. Are those new maintainers, or is it just a fork with more activity?

**Comment by samuel** [comment]
Unfortunately I have not had the time or energy to maintain this project. I can't speak to which fork is the best or most maintained, but I think it's at least important for me to make it clear that there won't be any more work on this repo. But in the interest of providing at least some path forward I've linked to https://github.com/go-zookeeper/zk
