### ISSUE TITLE
Application crashes on zk.Connect() if servers slice is empty

### ISSUE THREAD

**Issue by radu-munteanu** [samuel/go-zookeeper#53]
It should return an err, and not throwing some exceptions that crash the app. I manage to do a simple workaround, by making my own validation on servers list before calling zk.Connect(). Probably a small validation inside the ConnectWithDialer() would be nicer.

**Comment by samuel** [comment]
Makes sense. Fixed in master: https://github.com/samuel/go-zookeeper/commit/1bc9c36ddd72ddf1d59d47144074f4aacfad4af3

**Comment by radu-munteanu** [comment]
Fix comment (not sure if notifications work on the commit): Error should be put in constants near line 103: ErrConnectionClosed = errors.New("zk: connection closed")
