### ISSUE TITLE
Let outer know state changes immediately

### ISSUE THREAD

**Issue by siddontang** [samuel/go-zookeeper#57]
I know that we can use `State()` function to check current connection state, but can not know the state changes immediately. 

In `setState`, there is a `eventChan` but it can not used outer, only in test I know. Could you let it open? Maybe below:

```
func (c *Conn)StateCh() <-chan Event {
    return c.eventChan
}
```

Why I need this, if SessionExpired and  reconnect ok, we can not know it any way. So now we could only re-create a new connection when expired.

**Comment by samuel** [comment]
That same channel is returned from `Connect*` as the second value. It'll remain throughout the life of the `*Conn` instance.

`func ConnectWithDialer(servers []string, sessionTimeout time.Duration, dialer Dialer) (*Conn, <-chan Event, error) {`

**Comment by siddontang** [comment]
Sorry, I haven't seen this before, thank you very much. :-)
