### ISSUE TITLE
When you set on an empty path, the zookeeper will crash

### ISSUE THREAD

**Issue by rejoy** [samuel/go-zookeeper#62]
When you try setting data on an empty path, it will crash and burn your zookeeper server. And by this I mean data corruption, you need to empty your data directory and then restart it, otherwise nobody will be able to connect to it any more and will get a connection refused.

It would be nice to have an error if the path is empty, rather than letting the set happen and watching your zookeeper go down in style.

**Comment by fengjingchao** [comment]
Hi,

Can you give more details:
- Which version you are using
- The code snip that caused this
- Any suspicious logs?

Thanks!

**Comment by brian-brazil** [comment]
This is a bug in zookeeper, see https://issues.apache.org/jira/browse/ZOOKEEPER-2213

**Comment by samuel** [comment]
Thanks for reporting this.

While it certainly seems like the server should handle this more gracefully, I added a client side check to be safe.

**Comment by samuel** [comment]
I create a ticket to have the logic in this package match the Java client: https://github.com/samuel/go-zookeeper/issues/63

**Comment by rejoy** [comment]
Thanks guys, damn you work really fast :+1:
