### ISSUE TITLE
Validate path before sending to server

### ISSUE THREAD

**Issue by samuel** [samuel/go-zookeeper#63]
The Java client does a number on checks on paths sent to the server. This package should do the same.

https://github.com/apache/zookeeper/blob/26e8dd6e90726997a37965ef469e37a96ef7085f/src/java/main/org/apache/zookeeper/common/PathUtils.java#L43

**Comment by fengjingchao** [comment]
I'm actually going to fix it in ZOOKEEPER-2213. It should return KeeperException.BadArguments error.
