### ISSUE TITLE
Lock fails when sibling nodes have dashes in the names

### ISSUE THREAD

**Issue by jsternberg** [samuel/go-zookeeper#64]
If you have sibling nodes with dashes in their names, the code for "Lock" fails when it tries to parse a non-existent integer for the name.

Looking at the code, it also seems like it will fail if there are any siblings at all.

Do locks have to be done on a completely separate directory to ensure it works correctly?

**Comment by samuel** [comment]
Yeah, code has the assumption that the only children of the lock node are instances of the lock. I'll add a note to the documentation to be clearer.

**Comment by samuel** [comment]
https://github.com/samuel/go-zookeeper/commit/c86eba8e7e95efab81f6c0455332e49d39aed12f

Going to close this as "works as expected". Please feel free to open if you believe the behavior should be different.
