### ISSUE TITLE
Add TreeCache?

### ISSUE THREAD

**Issue by brian-brazil** [samuel/go-zookeeper#66]
As part of implementing service discovery of Twitter Serversets in Prometheus, I did a basic implementation of a TreeCache (http://curator.apache.org/curator-recipes/tree-cache.html) in Go.

As this is generally useful and not tied to Prometheus, I think it'd be a good idea to make it more generally available as part of this repository under some directory in this repository.

The code is at https://github.com/prometheus/prometheus/blob/master/retrieval/discovery/serverset.go#L194-372

Would you be willing in principle to accept this code into this repository?

Also, Are there any stubs for the zk client to aid unittesting of something like this? I couldn't find anything from a quick look.

**Comment by fabxc** [comment]
:+1:

**Comment by rafikk** [comment]
I need this functionality in a project as well and would prefer not to copy the code from Prometheus.

**Comment by zellyn** [comment]
I believe that (a) TreeCache would be very useful, and that (b) it would more appropriately live in a Curator project. Unfortunately, there are a couple of Go curator projects: I always forget which is the more active.

**Comment by basvanbeek** [comment]
@tevino has contributed the TreeCache recipe to https://github.com/curator-go/curator which is a fork of https://github.com/flier/curator.go since that project has been abandoned.

**Comment by tevino** [comment]
Like @zellyn said, it would be more appropriate to have a TreeCache recipe in a Curator project.

I found https://github.com/curator-go/curator is very close to the Java's Curator, then I contributed the TreeCache recipe, I hope more people could know or better, contribute to it.

FYI: https://github.com/curator-go/curator/issues/1
