### ISSUE TITLE
How to get sessionID of my own connection, I need to judge whether my connection is the owner of a node

### ISSUE THREAD

**Issue by ayrb13** [samuel/go-zookeeper#78]
How to get sessionID of my own connection, I need to judge whether my connection is the owner of a node.

I see that sessionID is a unexported field of conn

**Comment by dallasmarlow** [comment]
@ayrb13 i needed this as well, and opened https://github.com/samuel/go-zookeeper/pull/81

**Comment by nomis52** [comment]
Use conn. SessionID()

This can be closed.
