### ISSUE TITLE
Children method fails on receiving big list of children

### ISSUE THREAD

**Issue by alxzh** [samuel/go-zookeeper#89]
In file github.com/samuel/go-zookeeper/zk/conn.go on line 545 we grow buffer size to blen if blen is bigger than current buffer. Then in several places we decode stuff like:
 `_, err := decodePacket(buf[16:16+blen], res)`
which is obviously panics - because we get past slice boundary.

Fix is to change line 545 to look like:
`buf = make([]byte, blen+16)`

Can't create a pull request right now. But would appreciate if somebody could fix this in mainstream.

**Comment by azhavnerchik** [comment]
I created a pull request for this. https://github.com/samuel/go-zookeeper/pull/90
